//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_A_Prodavnica_racunarske_opreme.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_sr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_sr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekat_A_Prodavnica_racunarske_opreme.Resources.Language_sr", typeof(Language_sr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Zaposlenog.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Proizvode.
        /// </summary>
        public static string AddProducts {
            get {
                return ResourceManager.GetString("AddProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi Zaposleni.
        /// </summary>
        public static string AllEmployees {
            get {
                return ResourceManager.GetString("AllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iznos.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Kategoriju.
        /// </summary>
        public static string btnAddCategory {
            get {
                return ResourceManager.GetString("btnAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Proizvod.
        /// </summary>
        public static string btnAddProduct {
            get {
                return ResourceManager.GetString("btnAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        public static string BtnDark {
            get {
                return ResourceManager.GetString("BtnDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtriraj.
        /// </summary>
        public static string btnFilter {
            get {
                return ResourceManager.GetString("btnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svijetla.
        /// </summary>
        public static string BtnLight {
            get {
                return ResourceManager.GetString("BtnLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        public static string BtnLogIn {
            get {
                return ResourceManager.GetString("BtnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj fakturu.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj Izmjene.
        /// </summary>
        public static string btnSaveChanges {
            get {
                return ResourceManager.GetString("btnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj Nabavku.
        /// </summary>
        public static string btnSaveOrder {
            get {
                return ResourceManager.GetString("btnSaveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srebrna.
        /// </summary>
        public static string BtnSilver {
            get {
                return ResourceManager.GetString("BtnSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivan.
        /// </summary>
        public static string cbActive {
            get {
                return ResourceManager.GetString("cbActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj fakturu.
        /// </summary>
        public static string CInvoice {
            get {
                return ResourceManager.GetString("CInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Izdavanja.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi Zaposlene.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji Zaposlenog.
        /// </summary>
        public static string EmployeeDetails {
            get {
                return ResourceManager.GetString("EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema podataka za prikaz.
        /// </summary>
        public static string EmptyDataGrid {
            get {
                return ResourceManager.GetString("EmptyDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi Proizvodi.
        /// </summary>
        public static string gpAllP {
            get {
                return ResourceManager.GetString("gpAllP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostupni Proizvodi.
        /// </summary>
        public static string gpAvaibleP {
            get {
                return ResourceManager.GetString("gpAvaibleP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji fakture.
        /// </summary>
        public static string gpInvoiceD {
            get {
                return ResourceManager.GetString("gpInvoiceD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavke fakture.
        /// </summary>
        public static string gpInvoiceI {
            get {
                return ResourceManager.GetString("gpInvoiceI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakture.
        /// </summary>
        public static string gpInvoices {
            get {
                return ResourceManager.GetString("gpInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proizvodi Za Nabavku.
        /// </summary>
        public static string gpOrder {
            get {
                return ResourceManager.GetString("gpOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji Nabavke.
        /// </summary>
        public static string gpOrderD {
            get {
                return ResourceManager.GetString("gpOrderD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabavke.
        /// </summary>
        public static string gpOrders {
            get {
                return ResourceManager.GetString("gpOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string IName {
            get {
                return ResourceManager.GetString("IName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj Fakture.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena [KM].
        /// </summary>
        public static string IPrice {
            get {
                return ResourceManager.GetString("IPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina [kom].
        /// </summary>
        public static string IQuantity {
            get {
                return ResourceManager.GetString("IQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv Kategorije.
        /// </summary>
        public static string lbCatName {
            get {
                return ResourceManager.GetString("lbCatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupac.
        /// </summary>
        public static string lbCustomer {
            get {
                return ResourceManager.GetString("lbCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum zaposlenja:.
        /// </summary>
        public static string lbDate {
            get {
                return ResourceManager.GetString("lbDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum izdavanja.
        /// </summary>
        public static string lbIssueDate {
            get {
                return ResourceManager.GetString("lbIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menadžer.
        /// </summary>
        public static string lbManager {
            get {
                return ResourceManager.GetString("lbManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Kategorija.
        /// </summary>
        public static string lbNewCat {
            get {
                return ResourceManager.GetString("lbNewCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string LbPass {
            get {
                return ResourceManager.GetString("LbPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloga.
        /// </summary>
        public static string lbRole {
            get {
                return ResourceManager.GetString("lbRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodavač.
        /// </summary>
        public static string lbSeller {
            get {
                return ResourceManager.GetString("lbSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobavljač.
        /// </summary>
        public static string lbSupplier {
            get {
                return ResourceManager.GetString("lbSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava Na Sistem.
        /// </summary>
        public static string LbTitle {
            get {
                return ResourceManager.GetString("LbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno:.
        /// </summary>
        public static string lbTotal {
            get {
                return ResourceManager.GetString("lbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime korisnika.
        /// </summary>
        public static string LbUser {
            get {
                return ResourceManager.GetString("LbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešno ime ili lozinka.
        /// </summary>
        public static string LogInError1 {
            get {
                return ResourceManager.GetString("LogInError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposleni je neaktivan.
        /// </summary>
        public static string LogInError2 {
            get {
                return ResourceManager.GetString("LogInError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno kreiran zaposleni!.
        /// </summary>
        public static string ManagerMsgNotification {
            get {
                return ResourceManager.GetString("ManagerMsgNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno izvršena izmjena zaposlenog:.
        /// </summary>
        public static string ManagerMsgNotification1 {
            get {
                return ResourceManager.GetString("ManagerMsgNotification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno dodat novi proizvod!.
        /// </summary>
        public static string ManagerMsgNotification2 {
            get {
                return ResourceManager.GetString("ManagerMsgNotification2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno dodata nova kategorija!.
        /// </summary>
        public static string ManagerMsgNotification3 {
            get {
                return ResourceManager.GetString("ManagerMsgNotification3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno kreirana nabavka!.
        /// </summary>
        public static string ManagerMsgNotification4 {
            get {
                return ResourceManager.GetString("ManagerMsgNotification4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string MenuLang {
            get {
                return ResourceManager.GetString("MenuLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string MenuLangEn {
            get {
                return ResourceManager.GetString("MenuLangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string MenuLangSr {
            get {
                return ResourceManager.GetString("MenuLangSr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string NameEmp {
            get {
                return ResourceManager.GetString("NameEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naruči Od Dobavljača.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Nabavke.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena [KM].
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Proizvoda.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proizvodi.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina [kom].
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema dovoljno proizvoda na stanju! Dostupno :.
        /// </summary>
        public static string SellerErrorMsg1 {
            get {
                return ResourceManager.GetString("SellerErrorMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite validnu količinu proizvoda.
        /// </summary>
        public static string SellerErrorMsg2 {
            get {
                return ResourceManager.GetString("SellerErrorMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno kreirana faktura!.
        /// </summary>
        public static string SellerMsgNotification {
            get {
                return ResourceManager.GetString("SellerMsgNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite ukloniti stavku.
        /// </summary>
        public static string SellerMsgRemove1 {
            get {
                return ResourceManager.GetString("SellerMsgRemove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda uklanjanjа.
        /// </summary>
        public static string SellerMsgRemove2 {
            get {
                return ResourceManager.GetString("SellerMsgRemove2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popunite sva obavezna polja!.
        /// </summary>
        public static string SellerMsgWarning1 {
            get {
                return ResourceManager.GetString("SellerMsgWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string SurrnameEmp {
            get {
                return ResourceManager.GetString("SurrnameEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodavnica računarske opreme.
        /// </summary>
        public static string Title_LogInWindow {
            get {
                return ResourceManager.GetString("Title_LogInWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodavnica računarske opreme - &apos;{0}&apos;.
        /// </summary>
        public static string Title_ManagerWindow {
            get {
                return ResourceManager.GetString("Title_ManagerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodavnica računarske opreme - &apos;{0}&apos;.
        /// </summary>
        public static string Title_SellerWindow {
            get {
                return ResourceManager.GetString("Title_SellerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtriraj po kategoriji.
        /// </summary>
        public static string txtFilterCategory {
            get {
                return ResourceManager.GetString("txtFilterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtriraj po ID.
        /// </summary>
        public static string txtFilterId {
            get {
                return ResourceManager.GetString("txtFilterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtriraj po nazivu.
        /// </summary>
        public static string txtFilterName {
            get {
                return ResourceManager.GetString("txtFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string txtPhone {
            get {
                return ResourceManager.GetString("txtPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga po nazivu.
        /// </summary>
        public static string txtSearch {
            get {
                return ResourceManager.GetString("txtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string txtSurrname {
            get {
                return ResourceManager.GetString("txtSurrname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve Fakture.
        /// </summary>
        public static string ViewInvoice {
            get {
                return ResourceManager.GetString("ViewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve Nabavke.
        /// </summary>
        public static string ViewOrders {
            get {
                return ResourceManager.GetString("ViewOrders", resourceCulture);
            }
        }
    }
}
