//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_A_Prodavnica_racunarske_opreme.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekat_A_Prodavnica_racunarske_opreme.Resources.Language_en", typeof(Language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Products.
        /// </summary>
        public static string AddProducts {
            get {
                return ResourceManager.GetString("AddProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Employees.
        /// </summary>
        public static string AllEmployees {
            get {
                return ResourceManager.GetString("AllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string btnAddCategory {
            get {
                return ResourceManager.GetString("btnAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string btnAddProduct {
            get {
                return ResourceManager.GetString("btnAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string BtnDark {
            get {
                return ResourceManager.GetString("BtnDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string btnFilter {
            get {
                return ResourceManager.GetString("btnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string BtnLight {
            get {
                return ResourceManager.GetString("BtnLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string BtnLogIn {
            get {
                return ResourceManager.GetString("BtnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save invoice.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string btnSaveChanges {
            get {
                return ResourceManager.GetString("btnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Order.
        /// </summary>
        public static string btnSaveOrder {
            get {
                return ResourceManager.GetString("btnSaveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string BtnSilver {
            get {
                return ResourceManager.GetString("BtnSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string cbActive {
            get {
                return ResourceManager.GetString("cbActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create invoice.
        /// </summary>
        public static string CInvoice {
            get {
                return ResourceManager.GetString("CInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issue.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Employee.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        public static string EmployeeDetails {
            get {
                return ResourceManager.GetString("EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        public static string EmptyDataGrid {
            get {
                return ResourceManager.GetString("EmptyDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        public static string gpAllP {
            get {
                return ResourceManager.GetString("gpAllP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaible Products.
        /// </summary>
        public static string gpAvaibleP {
            get {
                return ResourceManager.GetString("gpAvaibleP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Details.
        /// </summary>
        public static string gpInvoiceD {
            get {
                return ResourceManager.GetString("gpInvoiceD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Items.
        /// </summary>
        public static string gpInvoiceI {
            get {
                return ResourceManager.GetString("gpInvoiceI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string gpInvoices {
            get {
                return ResourceManager.GetString("gpInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products For Order.
        /// </summary>
        public static string gpOrder {
            get {
                return ResourceManager.GetString("gpOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string gpOrderD {
            get {
                return ResourceManager.GetString("gpOrderD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Orders.
        /// </summary>
        public static string gpOrders {
            get {
                return ResourceManager.GetString("gpOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string IName {
            get {
                return ResourceManager.GetString("IName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price [BAM].
        /// </summary>
        public static string IPrice {
            get {
                return ResourceManager.GetString("IPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity [pcs].
        /// </summary>
        public static string IQuantity {
            get {
                return ResourceManager.GetString("IQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string lbCatName {
            get {
                return ResourceManager.GetString("lbCatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string lbCustomer {
            get {
                return ResourceManager.GetString("lbCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of employment:.
        /// </summary>
        public static string lbDate {
            get {
                return ResourceManager.GetString("lbDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of issue.
        /// </summary>
        public static string lbIssueDate {
            get {
                return ResourceManager.GetString("lbIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string lbManager {
            get {
                return ResourceManager.GetString("lbManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string lbNewCat {
            get {
                return ResourceManager.GetString("lbNewCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LbPass {
            get {
                return ResourceManager.GetString("LbPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lbRole {
            get {
                return ResourceManager.GetString("lbRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string lbSeller {
            get {
                return ResourceManager.GetString("lbSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string lbSupplier {
            get {
                return ResourceManager.GetString("lbSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Log In.
        /// </summary>
        public static string LbTitle {
            get {
                return ResourceManager.GetString("LbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string lbTotal {
            get {
                return ResourceManager.GetString("lbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LbUser {
            get {
                return ResourceManager.GetString("LbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string LogInError1 {
            get {
                return ResourceManager.GetString("LogInError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive employee.
        /// </summary>
        public static string LogInError2 {
            get {
                return ResourceManager.GetString("LogInError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee successfully created!.
        /// </summary>
        public static string ManagerMsgNotification {
            get {
                return ResourceManager.GetString("ManagerMsgNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully executed change of employee:.
        /// </summary>
        public static string ManagerMsgNotification1 {
            get {
                return ResourceManager.GetString("ManagerMsgNotification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added new product!.
        /// </summary>
        public static string ManagerMsgNotification2 {
            get {
                return ResourceManager.GetString("ManagerMsgNotification2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added new category!.
        /// </summary>
        public static string ManagerMsgNotification3 {
            get {
                return ResourceManager.GetString("ManagerMsgNotification3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order successfully created!.
        /// </summary>
        public static string ManagerMsgNotification4 {
            get {
                return ResourceManager.GetString("ManagerMsgNotification4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuLang {
            get {
                return ResourceManager.GetString("MenuLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string MenuLangEn {
            get {
                return ResourceManager.GetString("MenuLangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string MenuLangSr {
            get {
                return ResourceManager.GetString("MenuLangSr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameEmp {
            get {
                return ResourceManager.GetString("NameEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order From A Supplier.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price [BAM].
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity [pcs].
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough products available! Available:.
        /// </summary>
        public static string SellerErrorMsg1 {
            get {
                return ResourceManager.GetString("SellerErrorMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input valid quantity of products.
        /// </summary>
        public static string SellerErrorMsg2 {
            get {
                return ResourceManager.GetString("SellerErrorMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice successfully created!.
        /// </summary>
        public static string SellerMsgNotification {
            get {
                return ResourceManager.GetString("SellerMsgNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove item.
        /// </summary>
        public static string SellerMsgRemove1 {
            get {
                return ResourceManager.GetString("SellerMsgRemove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm removal.
        /// </summary>
        public static string SellerMsgRemove2 {
            get {
                return ResourceManager.GetString("SellerMsgRemove2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all required fields!.
        /// </summary>
        public static string SellerMsgWarning1 {
            get {
                return ResourceManager.GetString("SellerMsgWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrname.
        /// </summary>
        public static string SurrnameEmp {
            get {
                return ResourceManager.GetString("SurrnameEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer equipment store.
        /// </summary>
        public static string Title_LogInWindow {
            get {
                return ResourceManager.GetString("Title_LogInWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer equipment store - &apos;{0}&apos;.
        /// </summary>
        public static string Title_ManagerWindow {
            get {
                return ResourceManager.GetString("Title_ManagerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer equipment store - &apos;{0}&apos;.
        /// </summary>
        public static string Title_SellerWindow {
            get {
                return ResourceManager.GetString("Title_SellerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Category.
        /// </summary>
        public static string txtFilterCategory {
            get {
                return ResourceManager.GetString("txtFilterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by ID.
        /// </summary>
        public static string txtFilterId {
            get {
                return ResourceManager.GetString("txtFilterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Name.
        /// </summary>
        public static string txtFilterName {
            get {
                return ResourceManager.GetString("txtFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string txtPhone {
            get {
                return ResourceManager.GetString("txtPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Name.
        /// </summary>
        public static string txtSearch {
            get {
                return ResourceManager.GetString("txtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrname.
        /// </summary>
        public static string txtSurrname {
            get {
                return ResourceManager.GetString("txtSurrname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Invoices.
        /// </summary>
        public static string ViewInvoice {
            get {
                return ResourceManager.GetString("ViewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Orders.
        /// </summary>
        public static string ViewOrders {
            get {
                return ResourceManager.GetString("ViewOrders", resourceCulture);
            }
        }
    }
}
